# Generated by Django 5.0.6 on 2024-05-30 05:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Salerecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_item', models.CharField(blank=True, max_length=100, null=True)),
                ('payee', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_received', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('date_of_sale', models.DateField(default=django.utils.timezone.now, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Divine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('received_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('date_of_stock', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('Category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_the_item', models.CharField(blank=True, max_length=100, null=True)),
                ('clearace_date', models.DateField(default=django.utils.timezone.now)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('complete', 'complete'), ('Pending', 'pending')], max_length=100)),
                ('Customers_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.salerecord')),
            ],
        ),
    ]
