# Generated by Django 5.0.6 on 2024-06-03 13:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacyapp', '0002_salerecord_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salerecord',
            name='date_of_sale',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='salerecord',
            name='name_of_the_item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.divine'),
        ),
    ]
